In [526]:
# import libraries needed
import numpy as np
import pandas as pd

In [527]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

sales_series = pd.Series(sales, name = 'Sales')

print(sales_series.name)
print(sales_series.dtype)
print(sales_series.values)
print(sales_series.index)


Sales
int64
[   0    5  155    0  518    0 1827  616  317  325]
RangeIndex(start=0, stop=10, step=1)


In [528]:
pd.Series(np.arange(5))

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [529]:
pd.Series(np.arange(5)).astype(float)

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [530]:
pd.Series(np.arange(5)).astype(bool)

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [531]:
pd.Series(np.arange(13)).astype('datetime64[M]')

0    1970-01-01
1    1970-02-01
2    1970-03-01
3    1970-04-01
4    1970-05-01
5    1970-06-01
6    1970-07-01
7    1970-08-01
8    1970-09-01
9    1970-10-01
10   1970-11-01
11   1970-12-01
12   1971-01-01
dtype: datetime64[s]

# Assignment 1: Series Basics

The code has been previded to create an array, `oil_array` from a dataframe column. 

* Convert `oil_array` into a Pandas Series, called `oil_series`. Give it a name!
* Return the name, dtype, size, and index of `oil_series`.

Take the mean of the values array. 

Then, convert the series to integer datatype and recalculate the mean. 


In [532]:
# create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("../retail/oil.csv").dropna()

# Grab 100 rows of oil prices
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])

oil_array

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

In [533]:
oil_series = pd.Series(oil_array, name = "Oil prices")


In [534]:
print(oil_series.mean())

51.128299999999996


# Assignment 2:  Accessing Series Data

* Set the date series, which has been created below, to be the index of the oil price series created in assignment 1.


* Then, take the mean of the first 10 and last 10 prices of the series.


* Finally, grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.

In [535]:
# extract date column from oil DataFrame and grab first 100 rows

dates = pd.Series(oil["date"]).iloc[1000:1100]

In [536]:
oil_series.index = dates
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: Oil prices, Length: 100, dtype: float64

In [537]:

mean_first_10 = oil_series.iloc[:10].mean()
mean_last_10 = oil_series.iloc[-10:].mean()
print(mean_first_10)
print(mean_last_10)


52.765
47.13


In [538]:
oil_series.loc["2017-01-01":"2017-01-07"].reset_index(drop=True)

0    52.36
1    53.26
2    53.77
3    53.98
Name: Oil prices, dtype: float64

# Assignment 3: Sorting and Filtering Series

* First, get the 10 lowest prices from the data. 
* Sort the 10 lowest prices by date, starting with the most recent and ending with the oldest price.

* Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.

In [539]:
# list of dates to be used to solve bullet 3

dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-06",
    "2017-03-05",
    "2017-02-12",
    "2017-03-21",
    "2017-04-14",
    "2017-04-15",
]

In [540]:
ten_lowest = oil_series.sort_values().iloc[:10]
ten_lowest.sort_index(ascending = False)



date
2017-05-10    47.28
2017-05-09    45.84
2017-05-08    46.46
2017-05-05    46.23
2017-05-04    45.55
2017-03-27    47.02
2017-03-23    47.00
2017-03-22    47.29
2017-03-21    47.02
2017-03-14    47.24
Name: Oil prices, dtype: float64

In [541]:
mask = oil_series.index.isin(dates) & (oil_series <= 50)

oil_series.loc[mask]

date
2017-03-21    47.02
2017-05-03    47.79
Name: Oil prices, dtype: float64


# Assignment 4: Series Operations

* Increase the prices in the oil series by 10%, and add an additional 2 dollars per barrel on top of that.

* Then, create a series that represents the difference between each price and max price.

* Finally, extract the month from the string dates in the index and store them as an integer in their own series.

In [542]:
oil_series * 1.1 + 2
max_price = oil_series.max()
price_differences = (max_price - oil_series)
price_differences


date
2016-12-20    2.26
2016-12-21    3.04
2016-12-22    2.50
2016-12-23    2.47
2016-12-27    1.66
              ... 
2017-05-09    8.64
2017-05-10    7.20
2017-05-11    6.67
2017-05-12    6.65
2017-05-15    5.62
Name: Oil prices, Length: 100, dtype: float64

In [543]:
month = oil_series.index.str[5:7].astype(int)
pd.Series(month)

0     12
1     12
2     12
3     12
4     12
      ..
95     5
96     5
97     5
98     5
99     5
Name: date, Length: 100, dtype: int64

# Assignment 5: Series Aggregations

* Calculate the sum and mean of prices in the month of March. 

* Next, calculate how many prices were recorded in January and February.

* Then, calculate the 10th and 90th percentiles across all data.

* Finally, how often did integer dollar value (e.g. 51, 52) occur in the data? Normalize this to a percentage.   

In [544]:
march_mask = oil_series.index.str[5:7] == "03"

oil_series[march_mask].sum().round(2)

np.float64(1134.54)

In [545]:
oil_series[march_mask].mean().round(2)

np.float64(49.33)

In [546]:
jan_feb_mask = oil_series.index.str[5:7].isin(["01", "02"])
oil_series[jan_feb_mask].size #Fel i uppgift, där räknas även nov och dec med vilket ger 47.

39

In [547]:
oil_series.quantile([0.1, 0.9])


0.1    47.299
0.9    53.811
Name: Oil prices, dtype: float64

In [548]:
oil_series.astype("int").value_counts()

Oil prices
53    26
52    22
47    13
48    10
51     7
50     7
49     6
54     5
45     2
46     2
Name: count, dtype: int64

# Assignment 6



In [549]:
import pandas as pd
import numpy as np

my_series = pd.Series([np.nan] * 5)
my_series


0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [550]:
my_series.isna()

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [551]:
my_series = pd.Series([pd.NA] * 5)
my_series = my_series.astype("Int64")
my_series

0    <NA>
1    <NA>
2    <NA>
3    <NA>
4    <NA>
dtype: Int64

In [552]:
my_series = pd.Series(range(5))

In [553]:
my_series.loc[1:2] = pd.NA
my_series

0    0.0
1    NaN
2    NaN
3    3.0
4    4.0
dtype: float64

In [554]:
my_series.isna()

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [555]:
my_series.value_counts(dropna=False)

NaN    2
0.0    1
3.0    1
4.0    1
Name: count, dtype: int64

In [556]:
my_series.fillna(0)

0    0.0
1    0.0
2    0.0
3    3.0
4    4.0
dtype: float64

In [557]:
my_series.fillna(my_series.mean())

0    0.000000
1    2.333333
2    2.333333
3    3.000000
4    4.000000
dtype: float64

In [558]:
my_series.dropna()

0    0.0
3    3.0
4    4.0
dtype: float64

In [559]:
my_series.dropna().reset_index(drop=True)

0    0.0
1    3.0
2    4.0
dtype: float64

# Assignment 6: Missing Data

There were some erroneous prices in our data, so they were filled in with missing values.

Can you confirm the number of missing values in the price column? 

Once you’ve done that, fill the prices in with the median of the oil price series.

In [560]:
# Fill in two values with missing data

oil_series = oil_series.where(~oil_series.isin([51.44, 47.83]), pd.NA)

In [561]:
oil_series.isna().sum()

np.int64(2)

In [562]:
oil_series = oil_series.fillna(oil_series.median())


In [563]:
oil_series.isna().sum()


np.int64(0)

# Exercise 7: Apply and Where

Write a function that outputs ‘buy’ if price is less than the 90th percentile and ‘wait’ if it’s not. Apply it to the oil series.

Then, create a series that multiplies price by .9 if the date is ‘2016-12-23’ or ‘2017-05-10’, and 1.1 for all other dates. 

In [564]:
oil_series.quantile(0.9)

np.float64(53.811)

In [565]:
oil_series.apply(lambda x: 'Buy' if x < oil_series.quantile(0.5) else 'Wait')



date
2016-12-20    Wait
2016-12-21    Wait
2016-12-22     Buy
2016-12-23     Buy
2016-12-27    Wait
              ... 
2017-05-09     Buy
2017-05-10     Buy
2017-05-11     Buy
2017-05-12    Wait
2017-05-15     Buy
Name: Oil prices, Length: 100, dtype: object

In [566]:
np.where(oil_series.index.isin(['2016-12-23', '2017-05-10']),
         oil_series * 0.9,
         oil_series * 1.1,
         )

array([57.442 , 57.4255, 57.178 , 46.809 , 58.102 , 59.411 , 59.18  ,
       59.125 , 57.596 , 58.586 , 59.147 , 59.378 , 57.145 , 55.902 ,
       57.409 , 58.311 , 57.596 , 57.695 , 56.232 , 56.529 , 57.563 ,
       58.047 , 57.618 , 57.354 , 58.564 , 58.498 , 57.893 , 58.025 ,
       59.29  , 58.905 , 59.191 , 58.311 , 57.409 , 57.607 , 58.289 ,
       59.224 , 58.256 , 58.531 , 58.421 , 58.751 , 58.751 , 59.422 ,
       58.971 , 59.928 , 59.389 , 59.444 , 59.4   , 59.202 , 57.893 ,
       58.663 , 58.509 , 57.948 , 54.813 , 53.625 , 52.855 , 52.745 ,
       51.964 , 53.174 , 53.13  , 53.174 , 52.569 , 51.722 , 52.019 ,
       51.7   , 52.03  , 51.722 , 53.196 , 54.417 , 55.33  , 55.594 ,
       55.275 , 56.089 , 56.254 , 56.859 , 57.475 , 58.366 , 58.718 ,
       58.432 , 58.509 , 57.882 , 57.706 , 55.539 , 55.286 , 54.604 ,
       53.79  , 54.142 , 54.142 , 53.856 , 54.241 , 53.713 , 52.415 ,
       52.569 , 50.105 , 50.853 , 51.106 , 50.424 , 42.552 , 52.591 ,
       57.4255, 53.7

In [567]:
df = pd.DataFrame(oil_series)
df

Oil prices
date                  
2016-12-20      52.220
2016-12-21      52.205
2016-12-22      51.980
2016-12-23      52.010
2016-12-27      52.820
...                ...
2017-05-09      45.840
2017-05-10      47.280
2017-05-11      47.810
2017-05-12      52.205
2017-05-15      48.860

[100 rows x 1 columns]

In [568]:
df["new price"]=np.where(oil_series.index.isin(['2016-12-23', '2017-05-10']),
         oil_series * 0.9,
         oil_series * 1.1,
         )
df

Oil prices  new price
date                             
2016-12-20      52.220    57.4420
2016-12-21      52.205    57.4255
2016-12-22      51.980    57.1780
2016-12-23      52.010    46.8090
2016-12-27      52.820    58.1020
...                ...        ...
2017-05-09      45.840    50.4240
2017-05-10      47.280    42.5520
2017-05-11      47.810    52.5910
2017-05-12      52.205    57.4255
2017-05-15      48.860    53.7460

[100 rows x 2 columns]